title: azurefire
tagline: Setting the cloud on fire
logo: default-thumb.png
description: A place to stash whatever pops into my head, mostly about software.

# Your site's domain goes here. Leave localhost server or blank when working locally.
url: https://azurefire.net

# Owner/author information
owner:
  name: Ash Wilson
  avatar: cat-sniffer.jpg
  bio: >
    Ash Wilson writes code at Rackspace. His specialties include: developer tooling, from SDKs to
    Atom packages; plugging things into other things (they had to cover all the electrical sockets);
    and eggs benedict.
  email: smashwilson@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter: smashwilson
  facebook: kzintelepath
  github: smashwilson
  linkedin:
  instagram:
  lastfm:
  tumblr:
  hmfaysalsocial:
  # For Google Authorship https://plus.google.com/authorship
  google_plus: https://plus.google.com/u/0/+AshWilsonAway/

# Analytics and webmaster tools stuff goes here
google_analytics: UA-54367335-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: home
    url: /
  - title: archive
    url: /archive/
  - title: tags
    url: /tags/
  - title: about
    url: /about/


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/New_York
highlighter: pygments
future: true
markdown: kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  input: GFM

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include:
- .htaccess
exclude:
- '*.sh'
- README.md
- LICENSE
- Gemfile*

assets:
  sources:
  - _assets/javascripts
  - _assets/stylesheets
  - _assets/images
  - _assets/fonts
  cache: true
  gzip: false
  js_compressor: uglifier
  css_compressor: sass
