# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

ENV['RACK_ENV'] = 'test'

require_relative '../azure'
require 'rack/test'
require 'fileutils'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.include Rack::Test::Methods

  # Default to GMT so test cases run with a well-known timezone.
  ENV['TZ'] = 'GMT'

  def app
    Sinatra::Application
  end

  # Common paths.
  def fixt_root
    File.join(__dir__, 'fixtures')
  end

  def temp_root
    File.join(__dir__, '..', 'tmp')
  end

  def public_root
    File.join(temp_root, 'public')
  end

  # Path generation helpers
  def fixt_path *paths
    File.join(fixt_root, *paths)
  end

  def temp_path *paths
    File.join(temp_root, *paths)
  end

  def public_path *paths
    File.join(public_path, *paths)
  end

  # Temporary storage filesystem manipulation.

  def clear_temp!
    FileUtils.rm_r(temp_root, secure: true) if Dir.exists? temp_root
  end

  def create_temp!
    clear_temp!
    FileUtils.mkdir_p(temp_root)
    FileUtils.mkdir_p(public_root)
  end

  # Initialize test storage.
  config.before do
    create_temp!
    Settings.current = Settings.new(
      'post-dirs' => [fixt_root],
      'post-ext' => 'md',
      'data-root' => temp_root,
      'public-root' => public_root,
      'base-url' => 'http://example.com/',
      'qotd-paths' => fixt_path('fake-quotes.qotd')
    )
  end

  config.after do
    clear_temp!
  end
end
