#!/usr/bin/env ruby
#
# Publish all compiled assets to the CDN.

require 'yaml'
require 'fog'
require 'find'

asset_root = ARGV[0] || File.join(__dir__, '..', '_site', 'assets')

vars = %w{RACKSPACE_USERNAME RACKSPACE_APIKEY RACKSPACE_REGION RACKSPACE_CONTAINER}
exit 0 if vars.any? { |v| ENV[v].nil? || ENV[v].empty? }

@storage = Fog::Storage.new(
  provider: :rackspace,
  rackspace_username: ENV["RACKSPACE_USERNAME"],
  rackspace_api_key: ENV["RACKSPACE_APIKEY"],
  rackspace_region: ENV["RACKSPACE_REGION"],
  rackspace_cdn_ssl: true
)

@directory = @storage.directories.new(key: ENV["RACKSPACE_CONTAINER"])

puts 'Publishing static assets to cloud files:'

Find.find(asset_root) do |path|
  next unless File.file? path

  remote = File.basename path

  File.open(path) do |inf|
    @directory.files.create(
      key: remote,
      body: inf,
      access_control_allow_origin: 'https://azurefire.net'
    )
  end
  print '.'
end
puts

puts "Complete."
